version: 0.2

phases:
  install:
    runtime-versions:
      python: "3.8"
    commands:
      - pip install terraform
      - pip install openpolicyagent
  build:
    commands:
      - terraform init
      - terraform plan -out=tfplan -var-file="terraform.tfvars"
      - opa eval -i policies/main.rego -d tfplan -f json
