version: 0.2

phases:
  install:
    runtime-versions:
      python: "3.8"
    commands:
      # Ensure Terraform is installed in the build environment
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.11.4/terraform_1.11.4_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - curl -L -o opa https://openpolicyagent.org/downloads/v1.3.0/opa_linux_amd64_static
      - mv opa /usr/local/bin/
      - chmod 755 /usr/local/bin/opa
    finally:
      - terraform --version
      - opa version
  build:
    commands:
      - terraform init
      - terraform plan -out=tfplan
      - opa eval -d policies/main.rego -i tfplan -f json
